config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :tables do
      resources :reservations, only: [:index, :new, :create, :destroy]
      resources :staffs, only: [:index, :new, :create]
    end
  end
  post '/Register_staff', to: 'staffs#create', as: :register_staff

  get 'add_restaurant', to: 'restaurants#new', as: 'add_restaurant'

  get '/dashboard', to: 'restaurants#index'
  get '/staff_dashboard', to: 'restaurants#indexes'

  # # Only for User
  # get '/potahi', to: 'potahis#view'

  # First Routes of Rails 
  get '/', to: 'users#user'

  # Function Admin and User Registration
  get '/registration', to: 'users#registration'
  get '/Cregistration', to: 'civilians#registration'

  # Define route for the admin page
  get '/admin', to: 'users#index'

  # Define route for the staff page
  get '/staff', to: 'staffs#index'

  get '/index', to: 'staffs#index'

  #add Staff
  get '/add_staff', to: 'staffs#registration'
  post '/create_staff', to: 'staffs#create'

  #add admin
  post '/users', to: 'users#create'

  #add staff
  post '/Register_staff', to: 'staffs#create'
  

  get '/create_admin', to: 'users#registration'

  # Function for login
  post '/Adminsessions', to: 'sessions#create'
  post '/Staff_Sessions', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'logout'

  
  # Define the login page route if not already defined
  get '/login', to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :table
  validates :name, :email, :reservation_time, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :tables, dependent: :destroy
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_secure_password
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :restaurant
  has_many :reservations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @table = Table.find(params[:table_id])
    @reservations = @table.reservations
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @table = @restaurant.tables.find(params[:table_id])
    @reservation = @table.reservations.find(params[:id])
    # Add any other logic needed for the show action
  end

  def new
    @table = Table.find(params[:table_id])
    @reservation = @table.reservations.new
  end

  def create
    @table = Table.find(params[:table_id])
    @reservation = @table.reservations.new(reservation_params)
    if @reservation.save
      redirect_to restaurant_table_reservations_path(@table.restaurant, @table), notice: 'Reservation was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to restaurant_table_reservations_path(params[:restaurant_id], params[:table_id]), notice: 'Reservation was successfully deleted.'
  end

  private

  def reservation_params
    params.require(:reservation).permit(:name, :email, :reservation_time)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def indexes
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show
    # @restaurant is already set by before_action
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address) # Add other permitted parameters as needed
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: login_params[:email])
    staff = Staff.find_by(email: login_params[:email])

    if user && user.authenticate(login_params[:password])
      session[:user_id] = user.id
      redirect_to '/dashboard'

    elsif staff && staff.authenticate(login_params[:password])
      session[:staff_id] = staff.id
      redirect_to '/staff_dashboard' 

    else
      flash[:login_errors] = ['Invalid credentials!']
      redirect_to '/users' 
    end
  end

  def destroy
    session[:user_id] = nil
    session[:staff_id] = nil
    redirect_to '/' 
  end

  private

  def login_params
    params.require(:login).permit(:email, :password)
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

    def index
      # Your index action logic
    end
  
    def new
      @staff = Staff.new
    end
  
    def create
      logger.info "Staff Params: #{staff_params.inspect}"
      @staff = Staff.new(staff_params)
      if @staff.save
        session[:staff_id] = @staff.id
        redirect_to '/dashboard'
      else
        flash[:register_errors] = @staff.errors.full_messages
        logger.error "Staff Registration Errors: #{@staff.errors.full_messages.inspect}"
        redirect_to '/'
      end
    end
  
    private
  
    def staff_params
      params.require(:staff).permit(:fname, :lname, :email, :password, :password_confirmation)
    end
  end
  

app/controllers/tables_controller.rb
class TablesController < ApplicationController
    def show
      @table = Table.find(params[:id])
      @reservations = @table.reservations
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        
    end

    def new
        @user = User.new
    end
      

    def create
        user = User.new(user_params)
        if user.save
            session[:user_id] = user.id
            redirect_to '/'
        else
            flash[:register_errors] = user.errors.full_messages
            redirect_to '/'
        end
    end

    private
        def user_params
            params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation) 
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<h1>Reservations for Table <%= @table.number %></h1>
<%= link_to 'New Reservation', new_restaurant_table_reservation_path(@table.restaurant, @table) %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Reservation Time</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.email %></td>
        <td><%= reservation.reservation_time %></td>
        <td>
          <form id="cancel-form-<%= reservation.id %>" action="<%= restaurant_table_reservation_path(reservation.table.restaurant, reservation.table, reservation) %>" method="POST" style="display: none;">
            <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <button type="submit" onclick="return confirm('Are you sure you want to cancel this reservation?')">Cancel</button>
          </form>
          <button type="button" onclick="document.getElementById('cancel-form-<%= reservation.id %>').submit();">Cancel</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_to "Logout", logout_path, method: :delete, class: "logout-button" %>

app/views/reservations/new.html.erb
<h1>New Reservation for Table <%= @table.number %></h1>
<%= form_with model: [@table.restaurant, @table, @reservation], local: true do |form| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
      <ul>
        <% @reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :reservation_time %>
    <%= form.datetime_select :reservation_time %>
  </div>
  <div>
    <%= form.submit 'Create Reservation' %>
  </div>
<% end %>


<%= button_to "Logout", logout_path, method: :delete, class: "logout-button" %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %> 
    </li>
    <li>
      <%= button_to "Delete this Restaurant", restaurant, method: :delete, class: "destroy-button", data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<%= button_to "Logout", logout_path, method: :delete, class: "logout-button" %>

<a class="color" href="/add_staff">Add a Staff</a>

app/views/restaurants/indexes.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %> 
    </li>
    <li>
      <%= button_to "Delete this Restaurant", restaurant, method: :delete, class: "destroy-button", data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<%= button_to "Logout", logout_path, method: :delete, class: "logout-button" %>

app/views/restaurants/new.html.erb
<h2>Create a new Restaurant</h2>
<%= form_with(model: @restaurant, url: restaurants_path, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  
  <!-- Add more fields here if needed -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<h2>Tables</h2>
<ul>
  <% @restaurant.tables.each do |table| %>
    <li><%= link_to "Table ##{table.number} (Seats: #{table.seats})", restaurant_table_path(@restaurant, table) %></li>
  <% end %>
</ul>


<%= button_to "Logout", logout_path, method: :delete, class: "logout-button" %>

app/views/staffs/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login Page</title>
<link rel="stylesheet" type="text/css" href="styles.css">
<style>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-size: cover;
    background-position: center; 
    background-repeat: no-repeat;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.form-container {
    background-color: rgba(255, 255, 255, 0.8);
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    max-width: 400px; /* Adjust the maximum width as needed */
    width: 100%; /* Added to ensure the container fills the available width */
    justify-content: center;
    align-items: center;
}

    .form {
        max-width: 400px;
        margin: 0 auto;
    }

    .input-field {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    .checkbox-field {
        margin-right: 10px;
    }

    .submit-button {
        width: 100%;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .submit-button:hover {
        background-color: #45a049;
    }

    .register {
        margin-top: 15px;
        font-size: 14px;
        text-align: center;
    }

    .color {
        color: #4CAF50;
    }
</style>
</head>
<body>
    <div class="form-container">
        <div class="form">
            <form action="/Staff_Sessions" method="POST" class="max-w-sm mx-auto">
                <div class="mb-5">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
                </div>
                <div class="mb-5">
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your Email</label>
                    <input type="email" id="email" name="login[email]" class="input-field" placeholder="" required />
                </div>
                <div class="mb-5">
                    <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your Password</label>
                    <input type="password" id="password" name="login[password]" class="input-field" required />
                </div>
                <div class="flex items-start mb-5">
                    <input id="remember" type="checkbox" value="" class="checkbox-field" required />
                    <label for="remember" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Remember me</label>
                </div>
                <button type="submit" class="submit-button">Staff Login</button>
                <a class="color" href="/">Back to Selection Form</a>
            </form>    
        </div>
    </div>
</body>
</html>

app/views/staffs/registration.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Background Image Example</title>
<style>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0; 
    background-size: cover;
    background-position: center; 
    background-repeat: no-repeat;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.form-container {
    background-color: rgba(255, 255, 255, 0.8);
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    max-width: 400px; /* Adjust the maximum width as needed */
    width: 100%; 
    color: black;
}

    .form {
        max-width: 400px;
        margin: 0 auto;
    }

    .input-field {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    .checkbox-field {
        margin-right: 10px;
    }

    .submit-button {
        width: 100%;
        padding: 10px;
        background-color: #4CAF50;
        color: black;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .submit-button:hover {
        background-color: #45a049;
    }

    .register {
        margin-top: 15px;
        font-size: 14px;
        text-align: center;
    }

    .color {
        color: #4CAF50;
    }
</style>
</head>
<body>
    <div class="background-image-container">
    <!-- Move the form outside of the background image container -->
    </div>

    <div class="form-container">
        <div class="form">
            <form action="/Register_staff" method="POST" class="max-w-sm mx-auto">
            <div class="mb-5">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
            </div>
            <div class="mb-5">
                <label for="fname" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">First Name</label>
                <input type="text" id="fname" name="staff[fname]" class="input-field" placeholder="" required />
            </div>
            <div class="mb-5">
                <label for="lname" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Last Name</label>
                <input type="text" id="lname" name="staff[lname]" class="input-field" placeholder="" required />
            </div>
            <div class="mb-5">
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                <input type="email" id="email" name="staff[email]" class="input-field" placeholder="" required />
            </div>
            <div class="mb-5">
                <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                <input type="password" id="password" name="staff[password]" class="input-field" required />
            </div>
            <div class="mb-5">
                <label for="password_confirmation" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password Confirmation</label>
                <input type="password" id="password_confirmation" name="staff[password_confirmation]" class="input-field" required />
            </div>
            <button type="submit" class="submit-button">Register Staff</button>
            </form>    
            <p class="register">Already an account? <a class="color" href="/index">Login Form</a>.</p>
        </div>
    </div>
</body>
</html>

app/views/tables/show.html.erb
<h1>Table <%= @table.number %> (Seats: <%= @table.seats %>)</h1>
<h2>Reservations</h2>
<ul>
  <% @reservations.each do |reservation| %>
    <li><%= reservation.name %> - <%= reservation.reservation_time %></li>
  <% end %>
</ul>
<%= link_to 'New Reservation', new_restaurant_table_reservation_path(@table.restaurant, @table) %>


<%= button_to "Logout", logout_path, method: :delete, class: "logout-button" %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login Page</title>
<link rel="stylesheet" type="text/css" href="styles.css">
<style>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f9; 
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.form-container {
    background-color: white;
    padding: 40px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    max-width: 400px; 
    width: 100%; 
    text-align: center;
}

.input-field {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
}

.checkbox-field {
    margin-right: 10px;
}

.submit-button {
    width: 100%;
    padding: 15px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-bottom: 15px;
    font-size: 16px;
    transition: background-color 0.3s, transform 0.3s;
}

.submit-button:hover {
    background-color: #45a049;
    transform: scale(1.05);
}

.submit-button:active {
    transform: scale(1);
}

.register {
    margin-top: 15px;
    font-size: 14px;
    text-align: center;
}

.color {
    color: #4CAF50;
}
</style>
</head>
<body>
    <div class="form-container">
        <div class="form">
            <form action="/Adminsessions" method="POST" class="max-w-sm mx-auto">
                <div class="mb-5">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
                </div>
                <div class="mb-5">
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your Email</label>
                    <input type="email" id="email" name="login[email]" class="input-field" placeholder="" required />
                </div>
                <div class="mb-5">
                    <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your Password</label>
                    <input type="password" id="password" name="login[password]" class="input-field" required />
                </div>
                <div class="flex items-start mb-5">
                    <input id="remember" type="checkbox" value="" class="checkbox-field" required />
                    <label for="remember" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Remember me</label>
                </div>
                <button type="submit" class="submit-button">Login</button>
            </form>    
        </div>
    </div>
</body>
</html>

app/views/users/registration.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Background Image Example</title>
<style>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-image: url('https://wallpapers.com/images/hd/cooking-background-dg5u6vitzfnv3mrw.jpg'); 
    background-size: cover;
    background-position: center; 
    background-repeat: no-repeat;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.form-container {
    background-color: rgba(255, 255, 255, 0.8);
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    max-width: 400px; /* Adjust the maximum width as needed */
    width: 100%; 
    color: black;
}

    .form {
        max-width: 400px;
        margin: 0 auto;
    }

    .input-field {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    .checkbox-field {
        margin-right: 10px;
    }

    .submit-button {
        width: 100%;
        padding: 10px;
        background-color: #4CAF50;
        color: black;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .submit-button:hover {
        background-color: #45a049;
    }

    .register {
        margin-top: 15px;
        font-size: 14px;
        text-align: center;
    }

    .color {
        color: #4CAF50;
    }
</style>
</head>
<body>
    <div class="background-image-container">
    <!-- Move the form outside of the background image container -->
    </div>

    <div class="form-container">
        <div class="form">
            <form action="/users" method="POST" class="max-w-sm mx-auto">
            <div class="mb-5">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
            </div>
            <div class="mb-5">
                <label for="fname" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">First Name</label>
                <input type="text" id="fname" name="user[fname]" class="input-field" placeholder="" required />
            </div>
            <div class="mb-5">
                <label for="lname" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Last Name</label>
                <input type="text" id="lname" name="user[lname]" class="input-field" placeholder="" required />
            </div>
            <div class="mb-5">
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                <input type="email" id="email" name="user[email]" class="input-field" placeholder="" required />
            </div>
            <div class="mb-5">
                <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                <input type="password" id="password" name="user[password]" class="input-field" required />
            </div>
            <div class="mb-5">
                <label for="password_confirmation" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password Confirmation</label>
                <input type="password" id="password_confirmation" name="user[password_confirmation]" class="input-field" required />
            </div>
            <button type="submit" class="submit-button">Register</button>
            </form>    
            <p class="register">Already an account? <a class="color" href="/index">Login Form</a>.</p>
        </div>
    </div>
</body>
</html>

app/views/users/user.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login Page</title>
<link rel="stylesheet" type="text/css" href="styles.css">
<style>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f9; 
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.form-container {
    background-color: white;
    padding: 40px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    max-width: 400px; 
    width: 100%; 
    text-align: center;
}

.input-field {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
}

.checkbox-field {
    margin-right: 10px;
}

.submit-button {
    width: 100%;
    padding: 15px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-bottom: 15px;
    font-size: 16px;
    transition: background-color 0.3s, transform 0.3s;
}

.submit-button:hover {
    background-color: #45a049;
    transform: scale(1.05);
}

.submit-button:active {
    transform: scale(1);
}

.register {
    margin-top: 15px;
    font-size: 14px;
    text-align: center;
}

.color {
    color: #4CAF50;
}
</style>
</head>
<body>
  <div class="form-container">
    <div class="form">
      <!-- Redirect to user page -->
      <form action="<%= staff_path %>" method="get" class="max-w-sm mx-auto">
        <button type="submit" class="submit-button">USER</button>
      </form>
      <!-- Redirect to admin page -->
      <form action="<%= admin_path %>" method="get" class="max-w-sm mx-auto">
        <button type="submit" class="submit-button">ADMIN</button>
      </form>
    </div>
  </div>
</body>
</html>